# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  default:
    deps: [preview]

  preview:
    cmds:
      - pulumi preview

  up:
    cmds:
      - pulumi up

  update-u-pkgs:
    cmds:
      - nix flake update
